version: "3.8"

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:80"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://host.docker.internal:8000
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
